name: dark-explorer

services:
  lite-explorer:
    image: ${LITE_EXPLORER_IMAGE:-local/block-explorer-light:dev}
    container_name: explorer-lite
    restart: unless-stopped
    ports:
      - "${EXPLORER_PORT:-25000}:80"
    environment:
      # We pass the URL here so envsubst can substitute it in the custom template
      - RPC_HTTP_URL=${RPC_HTTP_URL:-http://host.docker.internal:8545}
    volumes:
      - ./default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./docker-entrypoint.sh:/docker-entrypoint.d/40-overwrite-infura.sh:ro
    extra_hosts:
      # Allows the container to reach the host machine via host.docker.internal
      - "host.docker.internal:host-gateway"
